apiVersion: v1
kind: Service
metadata:
  name: {{ include "coweb.fullname" . }}  # Corrected template reference
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}  # Ensures NodePort is only set when required
      {{- end }}
  selector:
    app: {{ .Release.Name }}

