# Image details for the containerized web application
image:
  repository: localhost:5000/coweb-app
  tag: latest
  pullPolicy: Always  # Ensures the latest image is always pulled

# Kubernetes Deployment configurations
replicaCount: 6  # Adjust this based on your scaling needs
container:
  port: 80  # Ensure this matches your app's exposed port
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
# Kubernetes Service configurations
service:
  name: coweb-service
  type: NodePort  # Use LoadBalancer for external access
  port: 80
  targetPort: 80

# Namespace for deployment
namespace: coweb-ns

# Ingress (optional - enable if using ingress controller)
# ingress:
#   enabled: false
#   annotations: {}
#   hosts:
#     - host: coweb.local
#       paths:
#         - path: /
#           pathType: Prefix

serviceAccount:
  create: true  # Set to false if you don't need a service account
  name: coweb-sa  # Helm defaults to Release.Name if not specified

autoscaling:
  enabled: false  # Set to true if you want Horizontal Pod Autoscaler (HPA)
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5


ingress:
  enabled: true
  hosts:
    - host: local-app.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: coweb-service
              port: 80

