# Default values for coweb.
replicaCount: 8

# Container Image Configuration
image:
  repository: localhost:5000/coweb
  pullPolicy: Always
  tag: "latest"


containerPort: 80

# Service Configuration

service:
  name: coweb-service
  type: ClusterIP
  clusterIP: ""
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP




# Ingress Configuration (Disabled by Default)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resources Configuration
resources: {}
  # Example:
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Health Checks (Liveness & Readiness Probes)
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling Configuration (Disabled by Default)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Node & Pod Configuration
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true  # Ensure this is explicitly set
  name: ""  # Optional, override service account name

  
# ArgoCD Application Configuration

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coweb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Oreire/helm-kubdep.git
    targetRevision: main
    path: coweb/
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: localhost:5000/coweb-app
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: coweb-ns
  syncPolicy:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true





