---apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-repo-url.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: coweb-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true