---
apiVersion: v1
kind: Service
metadata:
  name: coweb-service
  namespace: coweb-ns
spec:
  type: NodePort
  selector:
    app: coweb
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080