name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd WEB
          docker build -t coweb-app:latest .

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f DEPLOY/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/coweb -n coweb-ns

      - name: Port forward service to localhost:31999
        run: |
          kubectl port-forward service/coweb-service 31999:80 -n coweb-ns &

      # - name: Set up ArgoCD CLI
      #   uses: argoproj-labs/setup-argocd-cli@v1
      #   with:
      #     version: 'latest'

      # - name: Sync ArgoCD application
      #   run: |
      #     argocd app sync coweb-app
      #     argocd app wait coweb-app --health --sync
      # - name: Notify deployment success
      #   run: |
      #     echo "Deployment to Kubernetes cluster successful!"
      #     echo "Application is now live at http://<your-node-ip>:30080"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}