name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd WEB
          docker build --no-cache -t coweb-app:latest .


      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f DEPLOY/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/coweb -n coweb-ns

      - name: Wait for coweb-service and port forward
        run: |
          while ! kubectl get svc coweb-service -n coweb-ns --no-headers; do
            echo "Waiting for coweb-service to be created..."
            sleep 5
          done
          echo "Service is available, starting port forwarding..."
          kubectl port-forward service/coweb-service 31888:80 -n coweb-ns &
          sleep 10
          echo "Port forwarding started. You can access the service at http://localhost:31888"